on:
  workflow_dispatch:

name: setup-r test

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'next'}

          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'next'}

          - {os: ubuntu-18.04,   r: 'release'}
          - {os: ubuntu-18.04,   r: 'next'}

    steps:
      - uses: actions/checkout@v2

      - uses: ./setup-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
