on:
  workflow_dispatch:
    inputs:
      inpos:
        description: 'OS, e.g. macos-latest, windows-latest, ubuntu-latest'
        required: true
        default: 'ubuntu-latest'
        type: string
      inprversion:
        description: 'R versions (comma separated)'
        required: true
        default: 'devel,next,release,latest,oldrel/1,4.0,3.6.x'
        type: string

name: setup-r test

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      rversions: ${{ steps.setup-matrix.outputs.rversions }}

    steps:
    - name: Set up build matrix
      id: setup-matrix
      run: |
        rversions=$(echo -n '["'; echo -n '${{ github.event.inputs.inprversion }}' | sed 's/,/","/g'; echo '"]')
        echo "rversions=$rversions" >> $GITHUB_OUTPUT

  R-CMD-check:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        r: ${{ fromJson(needs.setup-matrix.outputs.rversions) }}
    runs-on: ${{ github.event.inputs.inpos }}
    name: ${{ github.event.inputs.inpos }} (${{ matrix.r }})

    steps:
    - uses: actions/checkout@v3

    - uses: ./setup-r
      id: setup-r
      with:
        r-version: ${{ matrix.r }}
        use-public-rspm: true

    - name: Check output
      run: |
        echo Installed R ${{ steps.setup-r.outputs.installed-r-version }}

    - name: R version
      run: sessionInfo()
      shell: Rscript {0}
